// <auto-generated />
using DotNetCore_Day2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetCore_Day2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224160313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetCore_Day2.Model.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Shirt",
                            Price = 500m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mouse",
                            Price = 300m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Keyboard",
                            Price = 700m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shoes",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jeans",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Earaphone",
                            Price = 600m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
